name: irlib
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - alsa-lib=1.2.3=h516909a_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blosc=1.21.0=h9c3ff4c_0
  - boost-cpp=1.74.0=hc6e9bd1_3
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2021.5.30=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2021.5.30=py38h578d9bd_0
  - cfitsio=3.470=hb418390_7
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_0
  - cloudpickle=1.6.0=py_0
  - curl=7.77.0=hea6ffbf_0
  - cycler=0.10.0=py_2
  - cython=0.29.23=py38h709712a_0
  - dbus=1.13.6=h48d8840_2
  - decorator=5.0.9=pyhd8ed1ab_0
  - expat=2.4.1=h9c3ff4c_0
  - fiona=1.8.20=py38hdb5a769_0
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.10.4=h0708190_1
  - freexl=1.0.6=h7f98852_0
  - gdal=3.2.2=py38h507a4fd_5
  - geopandas=0.9.0=pyhd8ed1ab_0
  - geos=3.9.1=h9c3ff4c_2
  - geotiff=1.6.0=hcf90da6_5
  - gettext=0.19.8.1=h0b5b191_1005
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.68.2=h9c3ff4c_2
  - glib-tools=2.68.2=h9c3ff4c_2
  - gst-plugins-base=1.18.4=hf529b03_2
  - gstreamer=1.18.4=h76c114f_2
  - h5py=3.2.1=nompi_py38h9915d05_100
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - icu=68.1=h58526e2_0
  - ipykernel=5.5.5=py38hd0cf306_0
  - ipython=7.24.0=py38hd0cf306_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.0=py38h578d9bd_2
  - jpeg=9d=h36c2ea0_0
  - json-c=0.15=h98cffda_0
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py38h578d9bd_0
  - kealib=1.4.14=hcc255d8_2
  - kiwisolver=1.3.1=py38h1fd1430_1
  - krb5=1.19.1=hcc1bbae_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libblas=3.9.0=9_openblas
  - libcblas=3.9.0=9_openblas
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.77.0=h2574ce0_0
  - libdap4=3.20.6=hd7c4107_2
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_19
  - libgdal=3.2.2=h679344c_5
  - libgfortran-ng=9.3.0=hff62375_19
  - libgfortran5=9.3.0=hff62375_19
  - libglib=2.68.2=h3e27bee_2
  - libgomp=9.3.0=h2828fa1_19
  - libiconv=1.16=h516909a_0
  - libkml=1.3.0=h238a007_1013
  - liblapack=3.9.0=9_openblas
  - libllvm11=11.1.0=hf817b99_2
  - libnetcdf=4.8.0=nompi_hcd642e3_103
  - libnghttp2=1.43.0=h812cca2_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.15=pthreads_h8fe5266_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.3=hd57d9b9_0
  - librttopo=1.1.0=h1185371_6
  - libsodium=1.0.18=h36c2ea0_1
  - libspatialindex=1.9.3=h9c3ff4c_3
  - libspatialite=5.0.1=h20cb978_4
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-ng=9.3.0=h6de172a_19
  - libtiff=4.2.0=hbd63e13_2
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.0=h7f98852_2
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzip=1.7.3=h4de3113_0
  - lz4-c=1.9.3=h9c3ff4c_0
  - lzo=2.10=h516909a_1000
  - matplotlib=3.4.2=py38h578d9bd_0
  - matplotlib-base=3.4.2=py38hcc49a3a_0
  - matplotlib-inline=0.1.2=pyhd8ed1ab_2
  - mock=4.0.3=py38h578d9bd_1
  - munch=2.5.0=py_0
  - mysql-common=8.0.23=ha770c72_2
  - mysql-libs=8.0.23=h935591d_2
  - ncurses=6.2=h58526e2_4
  - nspr=4.30=h9c3ff4c_0
  - nss=3.65=hb5efdd6_0
  - numexpr=2.7.3=py38h51da96c_0
  - numpy=1.20.3=py38h9894fe3_1
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1k=h7f98852_0
  - pandas=1.2.4=py38h1abd341_0
  - parso=0.8.2=pyhd8ed1ab_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.2.0=py38ha0e1e83_1
  - pip=21.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - poppler=21.03.0=h93df280_0
  - poppler-data=0.4.10=0
  - postgresql=13.3=h2510834_0
  - proj=8.0.0=h277dcde_0
  - prompt-toolkit=3.0.18=pyha770c72_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pygments=2.9.0=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=3.1.0=py38h8eae827_0
  - pyqt=5.12.3=py38h578d9bd_7
  - pyqt-impl=5.12.3=py38h7400c14_7
  - pyqt5-sip=4.19.18=py38h709712a_7
  - pyqtchart=5.12=py38h7400c14_7
  - pyqtwebengine=5.12.1=py38h7400c14_7
  - pytables=3.6.1=py38hc386592_3
  - python=3.8.10=h49503c6_1_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2021.1=pyhd8ed1ab_0
  - pyzmq=22.1.0=py38h2035c66_0
  - qt=5.12.9=hda022c4_4
  - qtpy=1.9.0=py_0
  - readline=8.1=h46c0cb4_0
  - rtree=0.9.7=py38h02d302b_1
  - scipy=1.6.3=py38h7b17777_0
  - setuptools=49.6.0=py38h578d9bd_3
  - shapely=1.7.1=py38haeee4fe_4
  - six=1.16.0=pyh6c4a22f_0
  - spyder-kernels=1.9.4=py38h32f6830_0
  - sqlite=3.35.5=h74cdb3f_0
  - tiledb=2.2.9=h91fcb0e_0
  - tk=8.6.10=h21135ba_1
  - tornado=6.1=py38h497a2fe_1
  - traitlets=5.0.5=py_0
  - tzcode=2021a=h7f98852_1
  - tzdata=2021a=he74cb21_0
  - vitables=3.0.2=py38h1e0a361_1
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.36.2=pyhd3deb0d_0
  - wurlitzer=2.1.0=py38h578d9bd_0
  - xerces-c=3.2.3=h9d8b166_2
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.1=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - zeromq=4.3.4=h9c3ff4c_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.9=ha95c52a_0
prefix: /opt/anaconda3/envs/irlib
